### ISSUE TITLE
context deadline exceeded

### ISSUE THREAD

**Issue by asd13852710118** [srcrs/MagicBox#1]
执行每日投币的时候出现context deadline exceeded

**Comment by Mistarille224** [comment]
+1

**Comment by srcrs** [comment]
更新一下最新版本试试，B站投币判断有些改动
```
docker rmi srcrs/bilibili-task:latest
docker pull srcrs/bilibili-task:latest
```

**Comment by MichaelWangGitHub2** [comment]
个别视频还会出现context deadline exceeded,能否跳过或随机播放来跳过该视频
bilibili-task  | 2023/05/18 07:00:03 context deadline exceeded

**Comment by srcrs** [comment]
> 个别视频还会出现context deadline exceeded,能否跳过或随机播放来跳过该视频 bilibili-task | 2023/05/18 07:00:03 context deadline exceededbilibili任务| 2023/05/18 07:00:03 超过上下文截止日期

还有更多的日志信息吗，比如是哪些视频
