### ISSUE TITLE
MagicBox-0.2.4，Docker-24.0.4，CentOS-7.9-64位 获取二维码失败

### ISSUE THREAD

**Issue by yonzhfun** [srcrs/MagicBox#14]
[root@10-60-249-207 MagicBox-0.2.4]# pwd
/root/myDeployProject/MagicBox-0.2.4
[root@10-60-249-207 MagicBox-0.2.4]# ll
total 12
drwxr-xr-x 2 root root   26 Dec  7 21:14 configs
-rw-r--r-- 1 root root  234 Nov 23 00:57 docker-compose.yml
-rw-r--r-- 1 root root  839 Nov 23 00:57 install.sh
-rw-r--r-- 1 root root 1066 Nov 23 00:57 LICENSE
-rw-r--r-- 1 root root    0 Nov 23 00:57 MagicBox.log
[root@10-60-249-207 MagicBox-0.2.4]# docker compose run server bilibili login
2023-12-07T21:19:40.259+0800    INFO    当前版本: 0.2.0
2023-12-07T21:21:20.262+0800    ERROR   获取二维码失败  {"error": "context deadline exceeded"}
2023-12-07T21:21:20.262+0800    ERROR   获取二维码失败  {"error": "context deadline exceeded"}
[root@10-60-249-207 MagicBox-0.2.4]# 
[root@10-60-249-207 MagicBox-0.2.4]# 
[root@10-60-249-207 MagicBox-0.2.4]# 
[root@10-60-249-207 MagicBox-0.2.4]# docker --version
Docker version 24.0.4, build 3713ee1
![Docker部署获取二维码失败](https://github.com/srcrs/MagicBox/assets/101497679/976a101b-9309-4d64-8476-e6e1deed99ff)

**Comment by yonzhfun** [comment]
谢谢老哥，可以了(顺带解决一个issue)。上次搞好之后好久没关注新版本了

**Comment by srcrs** [comment]
好的
