### ISSUE TITLE
请教有道云笔记签到方法

### ISSUE THREAD

**Issue by denniszzg** [srcrs/MagicBox#15]
感谢您的项目。已经部署成功。参考 - [双十一京东自动申请价保助手 | Doduo' Site](https://blog.lass.cc/posts/double-eleven-jd-automatically-applies-for-price-insurance-assistant/) 教程，成功完成京东价保的设置。

我的问题是：

1. 青龙面板中，脚本管理 - jd脚本的 cron 和 定时任务 -  jd task 的定时规则 ，功能是重复的吗？
教程中
   jd脚本 cron: '0 41 8,16 ** *'
   jd task 定时规则：10 10 */2 * * *

~~2. 有道云笔记的签到是否也需要在定时任务中添加：`MagicBox/MagicBox_amd64_linux youdao exec`~~
[更新]：有道云笔记签到成功了

**Comment by srcrs** [comment]
好的
