### ISSUE TITLE
"exec: \"google-chrome\": executable file not found in $PATH"

### ISSUE THREAD

**Issue by cyxnzb** [srcrs/MagicBox#2]
好像会出现如果原生未装google-chrome报错的情况

**Comment by srcrs** [comment]
> 好像会出现如果原生未装google-chrome报错的情况

这个是在哪执行的，本地是依赖chrome浏览器环境的。

**Comment by cyxnzb** [comment]
> > 好像会出现如果原生未装google-chrome报错的情况
> 
> 这个是在哪执行的，本地是依赖chrome浏览器环境的。

我是直接在我的centos服务器上执行的，就是执行那个获取cookie程序的时候出现了这个

**Comment by cyxnzb** [comment]
> > 好像会出现如果原生未装google-chrome报错的情况
> 
> 这个是在哪执行的，本地是依赖chrome浏览器环境的。

不知道放在docker容器后会不会出现这个

**Comment by srcrs** [comment]
> > > 好像会出现如果原生未装google-chrome报错的情况
> 
> > 
> 
> > 这个是在哪执行的，本地是依赖chrome浏览器环境的。
> 
> 
> 
> 不知道放在docker容器后会不会出现这个

docker已经封装了chrome环境，使用类似这条命令即可

docker compose run server bilibili login

**Comment by cyxnzb** [comment]
> > > > 好像会出现如果原生未装google-chrome报错的情况
> > 
> > 
> > > 
> > 
> > 
> > > 这个是在哪执行的，本地是依赖chrome浏览器环境的。
> > 
> > 
> > 不知道放在docker容器后会不会出现这个
> 
> docker已经封装了chrome环境，使用类似这条命令即可
> 
> docker compose run server bilibili login

好滴，谢谢！
