### ISSUE TITLE
构建失败

### ISSUE THREAD

**Issue by 125540947** [srcrs/MagicBox#20]
![Screenshot_2024-04-06-06-51-06-71_61c78dc80ee02b53007c815fefe993e3](https://github.com/srcrs/MagicBox/assets/38803156/fb0d4d74-2118-4a64-bca1-678f772f83eb)
 [server builder 2/4] COPY . /src           1.9s
 => [server builder 3/4] WORKDIR /src          0.1s
 => ERROR [server builder 4/4] RUN go build  482.1s
 => [server stage-1 2/4] RUN apt-get update  116.0s
 ------
 > [server builder 4/4] RUN go build -ldflags "-s -w" -o ./bin/MagicBox .:
0.217 go: downloading github.com/tidwall/gjson v1.17.1
0.221 go: downloading github.com/DataHenHQ/useragent v0.1.0
30.27 go: downloading github.com/chromedp/cdproto v0.0.0-20240214232516-ad4608604e9e
60.30 go: downloading github.com/chromedp/chromedp v0.9.5
60.30 go: downloading github.com/robfig/cron/v3 v3.0.1
90.32 go: downloading go.uber.org/zap v1.24.0
120.4 go: downloading gopkg.in/natefinch/lumberjack.v2 v2.2.1
120.6 go: downloading github.com/google/uuid v1.6.0
482.1 utils/proxy.go:6:2: github.com/DataHenHQ/useragent@v0.1.0: Get "https://proxy.golang.org/github.com/%21data%21hen%21h%21q/useragent/@v/v0.1.0.zip": dial tcp 142.250.105.141:443: i/o timeout
482.1 utils/chrome.go:8:2: github.com/chromedp/cdproto@v0.0.0-20240214232516-ad4608604e9e: Get "https://proxy.golang.org/github.com/chromedp/cdproto/@v/v0.0.0-20240214232516-ad4608604e9e.zip": dial tcp 173.194.219.141:443: i/o timeout
482.1 utils/chrome.go:9:2: github.com/chromedp/cdproto@v0.0.0-20240214232516-ad4608604e9e: Get "https://proxy.golang.org/github.com/chromedp/cdproto/@v/v0.0.0-20240214232516-ad4608604e9e.zip": dial tcp 173.194.219.141:443: i/o timeout
482.1 utils/chrome.go:10:2: github.com/chromedp/chromedp@v0.9.5: Get "https://proxy.golang.org/github.com/chromedp/chromedp/@v/v0.9.5.zip": dial tcp 108.177.122.141:443: i/o timeout
482.1 workerflow/workerflow.go:10:2: github.com/google/uuid@v1.6.0: Get "https://proxy.golang.org/github.com/google/uuid/@v/v1.6.0.zip": dial tcp 142.250.105.141:443: i/o timeout
482.1 utils/global.go:4:2: github.com/robfig/cron/v3@v3.0.1: Get "https://proxy.golang.org/github.com/robfig/cron/v3/@v/v3.0.1.zip": dial tcp 108.177.122.141:443: i/o timeout
482.1 utils/utils.go:14:2: github.com/tidwall/gjson@v1.17.1: Get "https://proxy.golang.org/github.com/tidwall/gjson/@v/v1.17.1.zip": dial tcp 142.250.105.141:443: i/o timeout
482.1 utils/chrome.go:11:2: go.uber.org/zap@v1.24.0: Get "https://proxy.golang.org/go.uber.org/zap/@v/v1.24.0.zip": dial tcp 108.177.122.141:443: i/o timeout
482.1 utils/init.go:10:2: go.uber.org/zap@v1.24.0: Get "https://proxy.golang.org/go.uber.org/zap/@v/v1.24.0.zip": dial tcp 108.177.122.141:443: i/o timeout
482.1 utils/init.go:11:2: gopkg.in/natefinch/lumberjack.v2@v2.2.1: Get "https://p

**Comment by srcrs** [comment]
golang的代理换为国内源，或者开一下梯子
