### ISSUE TITLE
跟无头浏览器一样吗

### ISSUE THREAD

**Issue by TheHot** [srcrs/MagicBox#25]
用automa引擎跟使用puppeteer 无头浏览器引擎有啥不同吗，会不会被检测到

**Comment by srcrs** [comment]
只是用automa的工作流编辑能力，解析用的是go，底层调用的还是无头浏览器

**Comment by TheHot** [comment]
> 只是用automa的工作流编辑能力，解析用的是go，底层调用的还是无头浏览器

懂了，感谢大佬解惑
