### ISSUE TITLE
【已解决】在 main.go 文件中初始化配置时出现了 YAML 语法错误

### ISSUE THREAD

**Issue by zhfunner** [srcrs/MagicBox#6]
2023年7月30日13:12:35 拉的最新版, docker compose up -d后查看的日志:

panic: yaml: line 3: did not find expected key

goroutine 1 [running]:
main.initConfig()
        /src/main.go:110 +0x105
main.main()
        /src/main.go:27 +0x2e

**Comment by zhfunner** [comment]
醉了...也知道问题了.

是cookie引号问题...

但是,  聪明反被聪明误了,  以为`docker compose run server bilibili login`登录后输出的cookie需要提取某部分, 去格式化 JSON, 试了几部分都提示不对.  还试了从本地Chrome自己提cookie复制上去,  还是不对.  最后索性试下把输出的全部cookie都复制进去, 没想到就成了...哈哈哈

**Comment by srcrs** [comment]
> 醉了...也知道问题了.
> 
> 是cookie引号问题...
> 
> 但是, 聪明反被聪明误了, 以为`docker compose run server bilibili login`登录后输出的cookie需要提取某部分, 去格式化 JSON, 试了几部分都提示不对. 还试了从本地Chrome自己提cookie复制上去, 还是不对. 最后索性试下把输出的全部cookie都复制进去, 没想到就成了...哈哈哈

厉害👍，后面我再完善一下教程吧
